name: Playwright Tests
on: #event triggers section
 schedule: 
  - cron: '0 0 * * *'
 workflow_dispatch:
env:
 BASE_URL: https://playwright.dev/
jobs:
  test:
    timeout-minutes: 30
    runs-on: windows-latest
    strategy:
      matrix: # Parallel execution matrix
       browsers: [chromium, firefox, webkit]
    steps:
    - uses: actions/checkout@v4 #clone main repository to local runner
    - uses: actions/setup-node@v4 #Installs Node.js on the runner machine
      with:
        node-version: lts/*  #Selects the latest Long-Term Support version of Node.js
    - name: Install dependencies
      run: npm ci # install project-specific packages
    - name: Install Playwright Browsers
    #Installing only required browser at a time
      run: npx playwright install ${{matrix.browsers}} --with-deps
    - name: Run Playwright tests
    #running tests on all 3 browsers at the same time
      run: npx playwright test tests/example.spec.ts --projects = ${{matrix.browsers}}
    - uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
      # Appending the browser name ensures artifact files don't overwrite each other
        name: playwright-report ${{matrix.browsers}}
        path: playwright-report/
        retention-days: 30
